# Generated by Django 4.2.6 on 2023-12-03 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_tag_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='report_uuid',
            field=models.UUIDField(auto_created=True, default=1),
            preserve_default=False,
        ),
    ]
