# Generated by Django 4.2.6 on 2023-12-12 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_remove_report_report_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='expire_time',
            field=models.DateTimeField(db_index=True, verbose_name='when the post will no longer be available'),
        ),
    ]
